### ISSUE TITLE
which error code should I use for targetd ssl auth failure?

### ISSUE THREAD

**Issue by cathay4t** [libstorage/libstoragemgmt#245]
```
LUGIN_BUG(2): Unexpected exception Data: Traceback (most recent call last):
  File "/home/fge/vm/fge_Source/libstoragemgmt/python_binding/lsm/plugin/targetd/targetd.py", line 55, in target_wrapper
    return method(*args, **kwargs)
  File "/home/fge/vm/fge_Source/libstoragemgmt/python_binding/lsm/plugin/targetd/targetd.py", line 152, in plugin_register
    self._jsonrequest('access_group_list', default_error_handler=False)
  File "/home/fge/vm/fge_Source/libstoragemgmt/python_binding/lsm/plugin/targetd/targetd.py", line 972, in _jsonrequest
    response_obj = urlopen(request)
  File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib64/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib64/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 1243, in https_open
    context=self._context)
  File "/usr/lib64/python2.7/urllib2.py", line 1197, in do_open
    h.request(req.get_method(), req.get_selector(), req.data, headers)
  File "/usr/lib64/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib64/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib64/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib64/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib64/python2.7/httplib.py", line 1278, in connect
    server_hostname=server_hostname)
  File "/usr/lib64/python2.7/ssl.py", line 353, in wrap_socket
    _context=self)
  File "/usr/lib64/python2.7/ssl.py", line 601, in __init__
    self.do_handshake()
  File "/usr/lib64/python2.7/ssl.py", line 838, in do_handshake
    match_hostname(self.getpeercert(), self.server_hostname)
  File "/usr/lib64/python2.7/ssl.py", line 276, in match_hostname
    % (hostname, dnsnames[0]))
CertificateError: hostname u'fedr-targetd' doesn't match u'megadeth-vm-03.lab.bos.redhat.com'
```

**Comment by tasleson** [comment]
We really don't have an error for this, we can certainly add an error code for invalid certificate or use ErrorNumber.NETWORK_ERROR with the Certificate Error in the error message text.

**Comment by tasleson** [comment]
Addressed with https://github.com/libstorage/libstoragemgmt/pull/281
