### ISSUE TITLE
Got plugin bug when use non-ssl URI to connect a ssl targetd.

### ISSUE THREAD

**Issue by cathay4t** [libstorage/libstoragemgmt#246]
```
PLUGIN_BUG(2): Unexpected exception Data: Traceback (most recent call last):
  File "/home/fge/libstoragemgmt-code/python_binding/lsm/plugin/targetd/targetd.py", line 55, in target_wrapper
    return method(*args, **kwargs)
  File "/home/fge/libstoragemgmt-code/python_binding/lsm/plugin/targetd/targetd.py", line 152, in plugin_register
    self._jsonrequest('access_group_list', default_error_handler=False)
  File "/home/fge/libstoragemgmt-code/python_binding/lsm/plugin/targetd/targetd.py", line 972, in _jsonrequest
    response_obj = urlopen(request)
  File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/lib64/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 1244, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib64/python2.7/urllib2.py", line 1217, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/lib64/python2.7/httplib.py", line 1089, in getresponse
    response.begin()
  File "/usr/lib64/python2.7/httplib.py", line 444, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python2.7/httplib.py", line 408, in _read_status
    raise BadStatusLine(line)
BadStatusLine: ''
```

**Comment by tasleson** [comment]
I see that some other plugins will try both ssl & non-ssl when they get errors, not sure what we want to do for this.

**Comment by tasleson** [comment]
Addressed with https://github.com/libstorage/libstoragemgmt/pull/281
