### ISSUE TITLE
cache related operations/APIs are having issues

### ISSUE THREAD

**Issue by sharath-t** [libstorage/libstoragemgmt#358]
i was trying to implement cache related APIs (volume_write_cache_policy_update) for Arcconf plugin and found that there is an issue in the core  lsmcli module in cmdline.py file.
all the cache related functions `display_data` calls have the same input as that of `volume_cache_info`

below are the sequence of commands that i used

```[root@blrsm-lsm ~]# ./libstoragemgmt/plugin/arcconf/arcconf_lsmplugin -u arcconf:// list --type volumes
ID  | Name                   | SCSI VPD 0x83                    | Size          | Disabled | Pool ID | System ID | Disk Paths
-----------------------------------------------------------------------------------------------------------------------------
1:0 | LogicalDrv 0: /dev/sde | 600508b1001cd0aa041a1ad00d4c76fb | 1000170586112 | No       | 1:0     | 1         | /dev/sde  
1:1 | LogicalDrv 1: /dev/sdd | 600508b1001c3d59ca44dfc8270d3c21 | 3000511758336 | No       | 1:1     | 1         | /dev/sdd  
2:0 | LogicalDrv 0: /dev/sdc | 600508b1001c98e7bba4af87b55c709c | 220117073920  | No       | 2:0     | 2         | /dev/sdc  
[root@blrsm-lsm ~]# ./libstoragemgmt/plugin/arcconf/arcconf_lsmplugin -u arcconf:// volume-write-cache-policy-update -h
usage: arcconf_lsmplugin volume-write-cache-policy-update [-h] [-v] [-u <URI>]
                                                          [-P] [-H] [-t <SEP>]
                                                          [-e] [-f]
                                                          [-w CHILD_WAIT]
                                                          [--header] [-b] [-s]
                                                          --vol <VOL_ID>
                                                          --policy <POLICY>

optional arguments:
  -h, --help            show this help message and exit
  -v, --version         show program's version number and exit
  -u <URI>, --uri <URI>
                        Uniform resource identifier (env LSMCLI_URI)
  -P, --prompt          Prompt for password (env LSMCLI_PASSWORD)
  -H, --human           Print sizes in human readable format
                        (e.g., MiB, GiB, TiB)
  -t <SEP>, --terse <SEP>
                        Print output in terse form with "SEP" as a record separator
  -e, --enum            Display enumerated types as numbers instead of text
  -f, --force           Bypass confirmation prompt for data loss operations
  -w CHILD_WAIT, --wait CHILD_WAIT
                        Command timeout value in ms (default = 30s)
  --header              Include the header with terse
  -b                    Run the command async. Instead of waiting for completion.
                         Command will exit(7) and job id written to stdout.
  -s, --script          Displaying data in script friendly way with additional information(if exists)

cmd required arguments:
  --vol <VOL_ID>        Volume ID
  --policy <POLICY>     Write cache polices: WB, AUTO, WT which stand for "write back", "auto", "write through"
[root@blrsm-lsm ~]# ./libstoragemgmt/plugin/arcconf/arcconf_lsmplugin -u arcconf:// volume-write-cache-policy-update --vol 1:0 --policy WT
Traceback (most recent call last):
  File "/root/libstoragemgmt/python_binding/lsm/lsmcli/cmdline.py", line 68, in cmd_line_wrapper
    cli.process(c)
  File "/root/libstoragemgmt/python_binding/lsm/lsmcli/cmdline.py", line 2037, in process
    self.args.func(self.args)
  File "/root/libstoragemgmt/python_binding/lsm/lsmcli/cmdline.py", line 2125, in volume_write_cache_policy_update
    lsm_vol.id, *self.c.volume_cache_info(lsm_vol))])
TypeError: type object argument after * must be a sequence, not NoneType
[root@blrsm-lsm ~]# ./libstoragemgmt/plugin/arcconf/arcconf_lsmplugin -u arcconf:// volume-write-cache-policy-update --vol 1:0 --policy WT
PLUGIN_BUG(2): Got unexpected error volume_write_cache_policy_update() takes at least 3 arguments (2 given)`
```

So, on line 2125 of cmdline.py i want ahead and changed the `display_data` call with `volume_write_cache_policy_update` and post this i am getting the below error

`[root@blrsm-lsm ~]# ./libstoragemgmt/plugin/arcconf/arcconf_lsmplugin -u arcconf:// volume-write-cache-policy-update --vol 1:0 --policy WT
PLUGIN_BUG(2): Got unexpected error volume_write_cache_policy_update() takes at least 3 arguments (2 given) 
`

the `volume-write-cache-policy-update -h` specifies only 2 arguments as required.

need further debugging on this one.

**Comment by tasleson** [comment]
Some simple tests with `megaraid` plugin are working.

Signature of plugin method should be:

```python
def volume_write_cache_policy_update(self, volume, wcp, flags=Client.FLAG_RSVD):
```

The command line executes this method which appears to be successful for your plugin.  However, after this the command line then retrieves cache information and displays it.
```python
self.display_data(
            [
                VolumeRAMCacheInfo(
                    lsm_vol.id, *self.c.volume_cache_info(lsm_vol))])
```
Based on the stack trace
```
Traceback (most recent call last):
  File "/root/libstoragemgmt/python_binding/lsm/lsmcli/cmdline.py", line 68, in cmd_line_wrapper
    cli.process(c)
  File "/root/libstoragemgmt/python_binding/lsm/lsmcli/cmdline.py", line 2037, in process
    self.args.func(self.args)
  File "/root/libstoragemgmt/python_binding/lsm/lsmcli/cmdline.py", line 2125, in volume_write_cache_policy_update
    lsm_vol.id, *self.c.volume_cache_info(lsm_vol))])
TypeError: type object argument after * must be a sequence, not NoneType
```
It appears that the method `volume_cache_info` for the plugin is returning `None` instead of an array of values: `[write_cache_policy, write_cache_status, read_cache_policy, read_cache_status, phy_disk_cache]`

The constructor for `VolumeRAMCacheInfo` is:
```python
    def __init__(self, vol_id, write_cache_policy, write_cache_status,
                 read_cache_policy, read_cache_status, phy_disk_cache):
        self.vol_id = vol_id
        self.write_cache_policy = write_cache_policy
        self.write_cache_status = write_cache_status
        self.read_cache_policy = read_cache_policy
        self.read_cache_status = read_cache_status
        self.phy_disk_cache = phy_disk_cache
```

I can't comment on the other error you are seeing after you made modifications as I don't know what those modifications are.

**Comment by tasleson** [comment]
@sharath-t Any update on this?

**Comment by tasleson** [comment]
Closing as no response.  Please open a new issue if the problem persists.
