### ISSUE TITLE
Should raise INVALID_ARGUMENT error on incorrect URI scheme.

### ISSUE THREAD

**Issue by cathay4t** [libstorage/libstoragemgmt#46]
```
[fge@el7 ~]$ python
Python 2.7.5 (default, Feb 11 2014, 07:46:25)
[GCC 4.8.2 20140120 (Red Hat 4.8.2-13)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import lsm
>>> lsm_conn = lsm.Client("ontap//root@na-sim", "some_password")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/lsm/_client.py", line 137, in __init__
    u = uri_parse(uri, ['scheme'])
  File "/usr/lib/python2.7/site-packages/lsm/_common.py", line 278, in uri_parse
    'uri missing \"%s\" or is in invalid form' % r)
lsm._common.LsmError: PLUGIN_BUG(2): uri missing "scheme" or is in invalid form
```

**Comment by tasleson** [comment]
Addressed with d270f6d503615e98494664cdf9d570689efcb482
